---
swagger: "2.0"
info:
  version: "0.0.1"
  title: "Techorrect Test Dashboard"
host: "localhost"
basePath: "/dashboard"
schemes:
- "https"
consumes:
- "application/json"
produces:
- "application/json"
paths:
  /projects:
    get:
      description: "Gets the projects that the logged in user is authorized to view.\n"
      operationId: "projectsGET"
      parameters:
      - name: "x-access-token"
        in: "header"
        required: true
        type: "string"
      - name: "name"
        in: "query"
        required: false
        type: "string"
      responses:
        200:
          description: "Successful response"
          schema:
            type: "array"
            items:
              $ref: "#/definitions/Projects"
        403:
          description: "Forbidden"
      x-swagger-router-controller: "Default"
    post:
      description: "Creates a project\n"
      operationId: "projectsPOST"
      parameters:
      - name: "x-access-token"
        in: "header"
        required: true
        type: "string"
      - in: "body"
        name: "project"
        required: true
        schema:
          $ref: "#/definitions/Projects"
      responses:
        201:
          description: "Created"
          schema:
            $ref: "#/definitions/Projects"
        403:
          description: "Forbidden"
      x-swagger-router-controller: "Default"
    options:
      description: "Options operation\n"
      operationId: "projectsOPTIONS"
      parameters:
      - name: "x-access-token"
        in: "header"
        required: true
        type: "string"
      - name: "projectId"
        in: "path"
        required: true
        type: "string"
      responses:
        200:
          description: "OK"
      x-swagger-router-controller: "Default"
  /projects/{projectId}:
    get:
      description: "Gets one project\n"
      operationId: "projectsProjectIdGET"
      parameters:
      - name: "projectId"
        in: "path"
        required: true
        type: "string"
      - name: "x-access-token"
        in: "header"
        required: true
        type: "string"
      responses:
        200:
          description: "Successful response"
          schema:
            $ref: "#/definitions/Projects"
        403:
          description: "Forbidden"
      x-swagger-router-controller: "Default"
    put:
      description: "Updates a project\n"
      operationId: "projectsProjectIdPUT"
      parameters:
      - name: "x-access-token"
        in: "header"
        required: true
        type: "string"
      - name: "projectId"
        in: "path"
        required: true
        type: "string"
      - in: "body"
        name: "project"
        required: true
        schema:
          $ref: "#/definitions/Projects"
      responses:
        200:
          description: "Successful response"
          schema:
            $ref: "#/definitions/Projects"
        403:
          description: "Forbidden"
      x-swagger-router-controller: "Default"
    delete:
      description: "Deletes a project\n"
      operationId: "projectsProjectIdDELETE"
      parameters:
      - name: "x-access-token"
        in: "header"
        required: true
        type: "string"
      - name: "projectId"
        in: "path"
        required: true
        type: "string"
      responses:
        204:
          description: "Successfully deleted"
        403:
          description: "Forbidden"
      x-swagger-router-controller: "Default"
    options:
      description: "Options operation\n"
      operationId: "projectsProjectIdOPTIONS"
      parameters:
      - name: "projectId"
        in: "path"
        required: true
        type: "string"
      responses:
        200:
          description: "OK"
      x-swagger-router-controller: "Default"
  /projects/{projectId}/suites:
    get:
      description: "Gets the suites that have run for a given project\n"
      operationId: "projectsProjectIdSuitesGET"
      parameters:
      - name: "x-access-token"
        in: "header"
        required: true
        type: "string"
      - name: "projectId"
        in: "path"
        required: true
        type: "string"
      - name: "prevRuns"
        in: "query"
        required: false
        type: "integer"
        default: 25
      - name: "name"
        in: "query"
        required: false
        type: "string"
      responses:
        200:
          description: "Successful response"
          schema:
            type: "array"
            items:
              $ref: "#/definitions/Suites"
        403:
          description: "Forbidden"
      x-swagger-router-controller: "Default"
    post:
      description: "Creates a suite for a given project\n"
      operationId: "projectsProjectIdSuitesPOST"
      parameters:
      - name: "x-access-token"
        in: "header"
        required: true
        type: "string"
      - name: "projectId"
        in: "path"
        required: true
        type: "string"
      - in: "body"
        name: "suite"
        required: true
        schema:
          $ref: "#/definitions/Suites"
      responses:
        200:
          description: "OK"
        403:
          description: "Forbidden"
      x-swagger-router-controller: "Default"
    options:
      description: "Options operation\n"
      operationId: "projectsProjectIdSuitesOPTIONS"
      parameters:
      - name: "projectId"
        in: "path"
        required: true
        type: "string"
      responses:
        200:
          description: "OK"
      x-swagger-router-controller: "Default"
  /projects/{projectId}/suites/{suiteId}:
    get:
      description: "Gets one suite\n"
      operationId: "projectsProjectIdSuitesSuiteIdGET"
      parameters:
      - name: "x-access-token"
        in: "header"
        required: true
        type: "string"
      - name: "projectId"
        in: "path"
        required: true
        type: "string"
      - name: "suiteId"
        in: "path"
        required: true
        type: "string"
      responses:
        200:
          description: "Successful response"
          schema:
            $ref: "#/definitions/Suites"
        403:
          description: "Forbidden"
      x-swagger-router-controller: "Default"
    put:
      description: "Updates a suite\n"
      operationId: "projectsProjectIdSuitesSuiteIdPUT"
      parameters:
      - name: "x-access-token"
        in: "header"
        required: true
        type: "string"
      - name: "projectId"
        in: "path"
        required: true
        type: "string"
      - name: "suiteId"
        in: "path"
        required: true
        type: "string"
      - in: "body"
        name: "suite"
        required: true
        schema:
          $ref: "#/definitions/Suites"
      responses:
        200:
          description: "Successful response"
          schema:
            $ref: "#/definitions/Suites"
        403:
          description: "Forbidden"
      x-swagger-router-controller: "Default"
    delete:
      description: "Deletes a suite\n"
      operationId: "projectsProjectIdSuitesSuiteIdDELETE"
      parameters:
      - name: "x-access-token"
        in: "header"
        required: true
        type: "string"
      - name: "projectId"
        in: "path"
        required: true
        type: "string"
      - name: "suiteId"
        in: "path"
        required: true
        type: "string"
      responses:
        204:
          description: "Deleted"
        403:
          description: "Forbidden"
      x-swagger-router-controller: "Default"
    options:
      description: "Options operation\n"
      operationId: "projectsProjectIdSuitesSuiteIdOPTIONS"
      parameters:
      - name: "projectId"
        in: "path"
        required: true
        type: "string"
      - name: "suiteId"
        in: "path"
        required: true
        type: "string"
      responses:
        200:
          description: "OK"
      x-swagger-router-controller: "Default"
  /projects/{projectId}/suites/{suiteId}/{suiteRunId}:
    get:
      description: "Gets the test runs that ran as part of a particular suite run.\n"
      operationId: "projectsProjectIdSuitesSuiteIdSuiteRunIdGET"
      parameters:
      - name: "x-access-token"
        in: "header"
        required: true
        type: "string"
      - name: "projectId"
        in: "path"
        required: true
        type: "string"
      - name: "suiteId"
        in: "path"
        required: true
        type: "string"
      - name: "suiteRunId"
        in: "path"
        required: true
        type: "string"
      responses:
        200:
          description: "Successful response"
          schema:
            type: "array"
            items:
              $ref: "#/definitions/TestRuns"
        403:
          description: "Forbidden"
      x-swagger-router-controller: "Default"
  /projects/{projectId}/suites/{suiteId}/tests:
    get:
      description: "Gets the tests that have run for a given suite\n"
      operationId: "projectsProjectIdSuitesSuiteIdTestsGET"
      parameters:
      - name: "x-access-token"
        in: "header"
        required: true
        type: "string"
      - name: "projectId"
        in: "path"
        required: true
        type: "string"
      - name: "suiteId"
        in: "path"
        required: true
        type: "string"
      - name: "name"
        in: "query"
        required: false
        type: "string"
      responses:
        200:
          description: "Successful response"
          schema:
            type: "array"
            items:
              $ref: "#/definitions/Tests"
        403:
          description: "Forbidden"
      x-swagger-router-controller: "Default"
    post:
      description: "Creates a test that runs for a given suite\n"
      operationId: "projectsProjectIdSuitesSuiteIdTestsPOST"
      parameters:
      - name: "x-access-token"
        in: "header"
        required: true
        type: "string"
      - name: "projectId"
        in: "path"
        required: true
        type: "string"
      - name: "suiteId"
        in: "path"
        required: true
        type: "string"
      - in: "body"
        name: "test"
        required: true
        schema:
          $ref: "#/definitions/Tests"
      responses:
        200:
          description: "Successful response"
          schema:
            type: "array"
            items:
              $ref: "#/definitions/Tests"
        403:
          description: "Forbidden"
      x-swagger-router-controller: "Default"
    options:
      description: "Options operation\n"
      operationId: "projectsProjectIdSuitesSuiteIdTestsOPTIONS"
      parameters:
      - name: "projectId"
        in: "path"
        required: true
        type: "string"
      - name: "suiteId"
        in: "path"
        required: true
        type: "string"
      responses:
        200:
          description: "OK"
      x-swagger-router-controller: "Default"
  /projects/{projectId}/suites/{suiteId}/tests/{testId}:
    get:
      description: "Gets one test\n"
      operationId: "projectsProjectIdSuitesSuiteIdTestsTestIdGET"
      parameters:
      - name: "x-access-token"
        in: "header"
        required: true
        type: "string"
      - name: "projectId"
        in: "path"
        required: true
        type: "string"
      - name: "suiteId"
        in: "path"
        required: true
        type: "string"
      - name: "testId"
        in: "path"
        required: true
        type: "string"
      responses:
        200:
          description: "Successful response"
          schema:
            $ref: "#/definitions/Tests"
        403:
          description: "Forbidden"
      x-swagger-router-controller: "Default"
    put:
      description: "Updates a test\n"
      operationId: "projectsProjectIdSuitesSuiteIdTestsTestIdPUT"
      parameters:
      - name: "projectId"
        in: "path"
        required: true
        type: "string"
      - name: "suiteId"
        in: "path"
        required: true
        type: "string"
      - name: "testId"
        in: "path"
        required: true
        type: "string"
      - in: "body"
        name: "test"
        required: true
        schema:
          $ref: "#/definitions/Tests"
      responses:
        200:
          description: "Successful response"
          schema:
            $ref: "#/definitions/Tests"
        403:
          description: "Forbidden"
      x-swagger-router-controller: "Default"
    delete:
      description: "Deletes a test\n"
      operationId: "projectsProjectIdSuitesSuiteIdTestsTestIdDELETE"
      parameters:
      - name: "projectId"
        in: "path"
        required: true
        type: "string"
      - name: "suiteId"
        in: "path"
        required: true
        type: "string"
      - name: "testId"
        in: "path"
        required: true
        type: "string"
      responses:
        204:
          description: "Successfully deleted"
        403:
          description: "Forbidden"
      x-swagger-router-controller: "Default"
    options:
      description: "Options operation\n"
      operationId: "projectsProjectIdSuitesSuiteIdTestsTestIdOPTIONS"
      parameters:
      - name: "projectId"
        in: "path"
        required: true
        type: "string"
      - name: "suiteId"
        in: "path"
        required: true
        type: "string"
      - name: "testId"
        in: "path"
        required: true
        type: "string"
      responses:
        200:
          description: "OK"
      x-swagger-router-controller: "Default"
  /projects/{projectId}/suites/{suiteId}/tests/{testId}/testRuns:
    get:
      description: "Gets the runs for a given test.\n"
      operationId: "projectsProjectIdSuitesSuiteIdTestsTestIdTestRunsGET"
      parameters:
      - name: "x-access-token"
        in: "header"
        required: true
        type: "string"
      - name: "projectId"
        in: "path"
        required: true
        type: "string"
      - name: "suiteId"
        in: "path"
        required: true
        type: "string"
      - name: "testId"
        in: "path"
        required: true
        type: "string"
      responses:
        200:
          description: "Successful response"
          schema:
            type: "array"
            items:
              $ref: "#/definitions/TestRuns"
        403:
          description: "Forbidden"
      x-swagger-router-controller: "Default"
    post:
      description: "Creates a test run\n"
      operationId: "projectsProjectIdSuitesSuiteIdTestsTestIdTestRunsPOST"
      parameters:
      - name: "x-access-token"
        in: "header"
        required: true
        type: "string"
      - name: "projectId"
        in: "path"
        required: true
        type: "string"
      - name: "suiteId"
        in: "path"
        required: true
        type: "string"
      - name: "testId"
        in: "path"
        required: true
        type: "string"
      responses:
        200:
          description: "Successful response"
          schema:
            $ref: "#/definitions/TestRuns"
        403:
          description: "Forbidden"
      x-swagger-router-controller: "Default"
    options:
      description: "Options operation\n"
      operationId: "projectsProjectIdSuitesSuiteIdTestsTestIdTestRunsOPTIONS"
      parameters:
      - name: "projectId"
        in: "path"
        required: true
        type: "string"
      - name: "suiteId"
        in: "path"
        required: true
        type: "string"
      - name: "testId"
        in: "path"
        required: true
        type: "string"
      responses:
        200:
          description: "OK"
      x-swagger-router-controller: "Default"
  /projects/{projectId}/suites/{suiteId}/tests/{testId}/disable:
    post:
      description: "Disables the test from running\n"
      operationId: "projectsProjectIdSuitesSuiteIdTestsTestIdDisablePOST"
      parameters:
      - name: "x-access-token"
        in: "header"
        required: true
        type: "string"
      - name: "projectId"
        in: "path"
        required: true
        type: "string"
      - name: "suiteId"
        in: "path"
        required: true
        type: "string"
      - name: "testId"
        in: "path"
        required: true
        type: "string"
      - name: "prevRuns"
        in: "query"
        required: false
        type: "integer"
        default: 25
      responses:
        200:
          description: "Successful response"
          schema:
            type: "array"
            items:
              $ref: "#/definitions/TestRuns"
        403:
          description: "Forbidden"
      x-swagger-router-controller: "Default"
    options:
      description: "Options operation\n"
      operationId: "projectsProjectIdSuitesSuiteIdTestsTestIdDisableOPTIONS"
      parameters:
      - name: "projectId"
        in: "path"
        required: true
        type: "string"
      - name: "suiteId"
        in: "path"
        required: true
        type: "string"
      - name: "testId"
        in: "path"
        required: true
        type: "string"
      responses:
        200:
          description: "OK"
      x-swagger-router-controller: "Default"
  /projects/{projectId}/suites/{suiteId}/tests/{testId}/enable:
    post:
      description: "Disables the test from running\n"
      operationId: "projectsProjectIdSuitesSuiteIdTestsTestIdEnablePOST"
      parameters:
      - name: "x-access-token"
        in: "header"
        required: true
        type: "string"
      - name: "projectId"
        in: "path"
        required: true
        type: "string"
      - name: "suiteId"
        in: "path"
        required: true
        type: "string"
      - name: "testId"
        in: "path"
        required: true
        type: "string"
      responses:
        200:
          description: "Successful response"
          schema:
            type: "array"
            items:
              $ref: "#/definitions/TestRuns"
        403:
          description: "Forbidden"
      x-swagger-router-controller: "Default"
    options:
      description: "Options operation\n"
      operationId: "projectsProjectIdSuitesSuiteIdTestsTestIdEnableOPTIONS"
      parameters:
      - name: "projectId"
        in: "path"
        required: true
        type: "string"
      - name: "suiteId"
        in: "path"
        required: true
        type: "string"
      - name: "testId"
        in: "path"
        required: true
        type: "string"
      responses:
        200:
          description: "OK"
      x-swagger-router-controller: "Default"
  /projects/{projectId}/suites/{suiteId}/tests/{testId}/rerun:
    post:
      description: "Disables the test from running\n"
      operationId: "projectsProjectIdSuitesSuiteIdTestsTestIdRerunPOST"
      parameters:
      - name: "x-access-token"
        in: "header"
        required: true
        type: "string"
      - name: "projectId"
        in: "path"
        required: true
        type: "string"
      - name: "suiteId"
        in: "path"
        required: true
        type: "string"
      - name: "testId"
        in: "path"
        required: true
        type: "string"
      responses:
        200:
          description: "Successful response"
          schema:
            type: "array"
            items:
              $ref: "#/definitions/TestRuns"
        403:
          description: "Forbidden"
      x-swagger-router-controller: "Default"
    options:
      description: "Options operation\n"
      operationId: "projectsProjectIdSuitesSuiteIdTestsTestIdRerunOPTIONS"
      parameters:
      - name: "projectId"
        in: "path"
        required: true
        type: "string"
      - name: "suiteId"
        in: "path"
        required: true
        type: "string"
      - name: "testId"
        in: "path"
        required: true
        type: "string"
      responses:
        200:
          description: "OK"
      x-swagger-router-controller: "Default"
  /users:
    post:
      description: "Creates a user and authorizes that user for a list of projects.\n"
      operationId: "usersPOST"
      parameters:
      - name: "x-access-token"
        in: "header"
        required: true
        type: "string"
      - in: "body"
        name: "user"
        required: true
        schema:
          $ref: "#/definitions/Users"
      responses:
        201:
          description: "Successful response of created user object excluding password."
          schema:
            $ref: "#/definitions/Users"
        403:
          description: "Forbidden"
      x-swagger-router-controller: "Default"
    options:
      description: "Options operation\n"
      operationId: "usersOPTIONS"
      parameters: []
      responses:
        200:
          description: "OK"
      x-swagger-router-controller: "Default"
  /users/{username}:
    put:
      description: "Updates a user's password, admin status, or list of projects.\n"
      operationId: "usersUsernamePUT"
      parameters:
      - name: "x-access-token"
        in: "header"
        required: true
        type: "string"
      - name: "username"
        in: "path"
        required: true
        type: "string"
      - in: "body"
        name: "user"
        required: true
        schema:
          $ref: "#/definitions/Users"
      responses:
        200:
          description: "Successful response of updated user object excluding password."
          schema:
            $ref: "#/definitions/Users"
        403:
          description: "Forbidden"
      x-swagger-router-controller: "Default"
    delete:
      description: "Deletes a user.\n"
      operationId: "usersUsernameDELETE"
      parameters:
      - name: "x-access-token"
        in: "header"
        required: true
        type: "string"
      - name: "username"
        in: "path"
        required: true
        type: "string"
      responses:
        200:
          description: "Successfully deleted user."
        403:
          description: "Forbidden"
      x-swagger-router-controller: "Default"
    options:
      description: "Options operation\n"
      operationId: "usersUsernameOPTIONS"
      parameters:
      - name: "username"
        in: "path"
        required: true
        type: "string"
      responses:
        200:
          description: "OK"
      x-swagger-router-controller: "Default"
  /users/login:
    post:
      description: "Logs in a user so they can see their projects.\n"
      operationId: "usersLoginPOST"
      parameters:
      - in: "body"
        name: "user"
        required: true
        schema:
          $ref: "#/definitions/Users"
      responses:
        200:
          description: "Successful response returning an access token for the user."
          schema:
            type: "string"
            example: "sampleToken"
        401:
          description: "Unauthorized"
      x-swagger-router-controller: "Default"
    options:
      description: "Options operation\n"
      operationId: "usersLoginOPTIONS"
      parameters: []
      responses:
        200:
          description: "OK"
      x-swagger-router-controller: "Default"
  /users/logout:
    post:
      description: "Logs a user out.\n"
      operationId: "usersLogoutPOST"
      parameters:
      - name: "x-access-token"
        in: "header"
        required: true
        type: "string"
      responses:
        200:
          description: "Successful log out operation"
        401:
          description: "Unauthorized"
      x-swagger-router-controller: "Default"
    options:
      description: "Options operation\n"
      operationId: "usersLogoutOPTIONS"
      parameters: []
      responses:
        200:
          description: "OK"
      x-swagger-router-controller: "Default"
definitions:
  Projects:
    type: "object"
    properties:
      projectId:
        type: "string"
        example: "project1"
      name:
        type: "string"
        example: "Project name 1"
      healthySuites:
        type: "integer"
        example: 30
      unhealthySuites:
        type: "integer"
        example: 2
      healtyFailedLevel:
        type: "integer"
        example: 5
      healthySkippedLevel:
        type: "integer"
        example: 5
      healthyDisabledLevel:
        type: "integer"
        example: 10
    example:
      unhealthySuites: 2
      healtyFailedLevel: 5
      healthyDisabledLevel: 10
      name: "Project name 1"
      projectId: "project1"
      healthySkippedLevel: 5
      healthySuites: 30
  Suites:
    type: "object"
    properties:
      suiteId:
        type: "string"
        example: "suite1"
      name:
        type: "string"
        example: "Suite name 1"
      passingTests:
        type: "integer"
        example: 100
      failingTests:
        type: "integer"
        example: 4
      skippedTests:
        type: "integer"
        example: 3
      disabledTests:
        type: "integer"
        example: 3
      previousSuiteIds:
        type: "array"
        items:
          type: "string"
          example: ""
    example:
      skippedTests: 3
      suiteId: "suite1"
      disabledTests: 3
      failingTests: 4
      passingTests: 100
      name: "Suite name 1"
      previousSuiteIds:
      - ""
      - ""
  Tests:
    type: "object"
    properties:
      testId:
        type: "string"
        example: "test1"
      name:
        type: "string"
        example: "Test Name 1"
      currentPassed:
        type: "boolean"
        example: false
      skip:
        type: "boolean"
        example: false
      disable:
        type: "boolean"
        example: false
      rerun:
        type: "boolean"
        example: false
    example:
      currentPassed: false
      disable: false
      name: "Test Name 1"
      testId: "test1"
      skip: false
      rerun: false
  TestRuns:
    type: "object"
    properties:
      testId:
        type: "string"
        example: "test1"
      suiteRunId:
        type: "string"
        example: "suiteRun1"
      dateRun:
        type: "string"
        format: "date-time"
      passed:
        type: "boolean"
        example: true
      skipped:
        type: "boolean"
        example: false
      disabled:
        type: "boolean"
        example: false
      log:
        type: "string"
        example: "Test passed"
    example:
      log: "Test passed"
      suiteRunId: "suiteRun1"
      testId: "test1"
      dateRun: "2000-01-23T04:56:07.000+00:00"
      disabled: false
      passed: true
      skipped: false
  Users:
    type: "object"
    properties:
      username:
        type: "string"
      password:
        type: "string"
      admin:
        type: "boolean"
      authorizedProjects:
        type: "string"
    example:
      password: "password"
      admin: true
      username: "username"
      authorizedProjects: "authorizedProjects"
